In [1]:
import numpy as np

In [2]:
v = np.array([1,-1,2])
w = np.array([2,5,2])

In [3]:
print(v+w)

[3 4 4]


In [4]:
print(v-w)

[-1 -6  0]


In [5]:
print(3*v)

[ 3 -3  6]


In [6]:
l = np.linalg.norm(v)

In [7]:
print(l)

2.449489742783178


In [8]:
s = np.dot(v,w)
print(s)

1


In [9]:
p = np.array([[1,7],[2,1],[3,2]])
print(p)

[[1 7]
 [2 1]
 [3 2]]


In [10]:
q = np.array([[1,1],[1,-1],[1,0]])
print(q)

[[ 1  1]
 [ 1 -1]
 [ 1  0]]


In [11]:
c1 = np.add(p,q)
print(c1)

[[2 8]
 [3 0]
 [4 2]]


In [12]:
c1 = np.subtract(p,q)
print(c1)

[[0 6]
 [1 2]
 [2 2]]


In [13]:
R = np.array([[1,1,2],[1,2,1]])
print(R)

[[1 1 2]
 [1 2 1]]


In [15]:
C2 = np.dot(p,R)
print(C2)

[[ 8 15  9]
 [ 3  4  5]
 [ 5  7  8]]


In [16]:
det = np.linalg.det(C2)
print(det)

0.0


In [17]:
s2 = np.linalg.inv(C2)

LinAlgError: Singular matrix